version: "3"
services:
  uaifood:
    container_name: uaifood
    image: backend
    restart: unless-stopped
    build: .
    ports:
      - "5000:7500"
    links:
      - db
    depends_on:
      - db
    # command: npm run test
  db:
    container_name: db
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  
